### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by da-the-dev** [Abdenasser/neohtop#118]
**Describe the bug**
Neohtop reports high CPU usage for its own process. Upto 50% at times. My laptop's fans spin up once I open the program

**To Reproduce**
1. Open Neohtop
2. Notice the CPU usage

**Expected behavior**
CPU usage comparable to regular htop

**Screenshots**
![image](https://github.com/user-attachments/assets/8976edae-e454-42b5-9579-e15e268f2be1)

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Kernel: 6.12.1-arch1-1

**Comment by Abdenasser** [comment]
first I wouldn't compare a webkit based UI app with a TUI app, The percentage you see for a process's CPU usage is relative to a single core, not the whole CPU power. no way NeoHtop would cause your fans to go crazy unless you are running it on a potato.

I've seen NeoHtop goes to 12% sometimes on my M1 Pro for 1s refresh rate, on Windows 10 it barely cross 5%.

**Comment by da-the-dev** [comment]
> no way NeoHtop would cause your fans to go crazy unless you are running it on a potato.

kinda rude of you to assume that my pc is a potato. you could've at least ask for my specs before closing the issue. my cpu is 11th Gen Intel(R) Core(TM) i5-11300H. i wouldn't consider that a potato.

> no way NeoHtop would cause your fans to go crazy

i'm reporting you my observations, does not make sense for you to deny them

> I've seen NeoHtop goes to 12% sometimes on my M1 Pro for 1s refresh rate,

if you app reports 12% CPU usage on M1, i would consider optimizing it imho

> on Windows 10 it barely cross 5%

i would like to know your specs

the reason i opened up this issue is to let others report their observations on the performance of this app. i believe it is important for such a tool to have a low impact on the system. kde's system monitor reports below 7% CPU usage on my system and has way more features than neohtop. i'm not here to hate the app, i'm here to help improve it. i recommend you to reopen this issue, because "it works on my machine" was never a solution.

**Comment by stef204** [comment]
I am also experiencing the same issue on Archlinux.  High CPU usage (27%-35% range) getting my fans to rev up. My box completely different than @da-the-dev, common denominator is distro. </br>

[Here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=neohtop) is how the package is built, in case there is some compile-time flag or option which should be used (or not); perhaps there's something wrong with the `tauri.patch`?

I've also used the binary version from GH (so that's without the `tauri.patch`) but same behavior.

Anyway, love the app; but doesn't make sense from a user's pov that an app used to monitor others uses so much CPU (more than most other apps being run on same system.) 

As soon as I kill it, all goes back to "normal" levels, fans slow down, etc.

Noteworthy: the high CPU % seems to occur when the app is in focus.  If I go to a different screen entirely (IOW, `neohtop` is *not* in focus) and look at `htop` to monitor `neohtop`, and wait a bit, it comes down from 35% to about 5% and stays  there.  So could be UI related, perhaps?

Everything else is great, the theming, the info available, etc.  I'd like to use the app but I'd need this addressed to really find it useful and switch to it from `htop` or `atop`, etc.
