### ISSUE TITLE
Add a program build for Flatpak and Snap

### ISSUE THREAD

**Issue by Katze-942** [Abdenasser/neohtop#91]
Flatpak (Flathub) and Snap (Snapcraft) are a universal way to distribute programs for Linux. Programs installed via flatpak/snap run on any distribution.

In addition, your program can be easily found in Discover or GNOME Software, which is also a plus.

**Comment by Abdenasser** [comment]
good suggestion, thank you.. but closing as it's not a priority right now.

**Comment by ruxartic** [comment]
@Abdenasser how about now? could a flatpak be possible?

**Comment by Abdenasser** [comment]
I can review it if you submit a pr.

**Comment by Abdenasser** [comment]
this project is open source, and I really appreciate having new contributors.. show me some PRs instead of waiting for me to support every linux distribution and architecture and every app distribution method (the ones that already exist are good enough but doesn't mean I'm pushing back on others or not going to accept it if someone pushed a PR support a new one) easy and simple as this.

**Comment by zeenix** [comment]
> support every linux distribution and architecture and every app distribution method

That's the entire idea of flatpak: so you don't have to worry or care about all the million different distributions and that's why most Linux apps these days support flatpak (whether or not they provide packages of other distros).

**Comment by zeenix** [comment]
@Abdenasser well, it **is** an app distribution mechanism but distro-agnostic, available in many (most?) distributions and it's not really new (10 years old).
